# Generated by Django 3.1.6 on 2021-03-03 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BR', 'Bronnen'), ('LO', 'Lage opwekking'), ('HO', 'Hoge opwekking'), ('LA', 'Lage afgifte'), ('HA', 'Hoge afgifte')], max_length=2)),
                ('sub_category', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Leverancier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leverancier', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productnr', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=64)),
                ('vermogen', models.FloatField()),
                ('belasting', models.FloatField()),
                ('rendement', models.FloatField()),
                ('leverancier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keuzeschema.leverancier')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keuzeschema.category')),
            ],
        ),
    ]
